spring.application.name=purchase-order-service
server.port=8082

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@t9vr8xfm2n3t5a6x_low?TNS_ADMIN=C:/wallet
spring.datasource.username=BD_DEV
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
